# Dependabot will run on day 24 of each month at 02:56 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '25 2 13 * *'
    open-pull-requests-limit: 30
    versioning-strategy: 'increase'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    cooldown:
      default-days: 7

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '25 2 13 * *'
    open-pull-requests-limit: 30
    target-branch: 'dependabot'
